// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKSyG_jhCkFYe5JS1rVLpp7DzBQwnbYuY',
    appId: '1:892348103935:web:7743de10ac7bcc1f4be0ca',
    messagingSenderId: '892348103935',
    projectId: 'fooddelivery-8d314',
    authDomain: 'fooddelivery-8d314.firebaseapp.com',
    storageBucket: 'fooddelivery-8d314.firebasestorage.app',
    measurementId: 'G-QQ8SFN3HSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW0V0rffMHVFg0GdVd3KEH1Os-ERB26IU',
    appId: '1:892348103935:android:e099af936cbd407d4be0ca',
    messagingSenderId: '892348103935',
    projectId: 'fooddelivery-8d314',
    storageBucket: 'fooddelivery-8d314.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqovdHamMD55roC_idBbbPm59R2ON98fA',
    appId: '1:892348103935:ios:b7e4a579bb216b794be0ca',
    messagingSenderId: '892348103935',
    projectId: 'fooddelivery-8d314',
    storageBucket: 'fooddelivery-8d314.firebasestorage.app',
    iosBundleId: 'com.example.muDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqovdHamMD55roC_idBbbPm59R2ON98fA',
    appId: '1:892348103935:ios:b7e4a579bb216b794be0ca',
    messagingSenderId: '892348103935',
    projectId: 'fooddelivery-8d314',
    storageBucket: 'fooddelivery-8d314.firebasestorage.app',
    iosBundleId: 'com.example.muDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKSyG_jhCkFYe5JS1rVLpp7DzBQwnbYuY',
    appId: '1:892348103935:web:cccc5adec307bd154be0ca',
    messagingSenderId: '892348103935',
    projectId: 'fooddelivery-8d314',
    authDomain: 'fooddelivery-8d314.firebaseapp.com',
    storageBucket: 'fooddelivery-8d314.firebasestorage.app',
    measurementId: 'G-38V251HRGR',
  );
}
